### ISSUE TITLE
短链二维码炸了

### ISSUE THREAD

**Issue by zkysimon** [urldl/url_Shortny#1]
短链二维码炸了
![](https://pic.rmb.bdstatic.com/bjh/a133616c4bf565e6ceecb00750ec23fb.png)

**Comment by urldl** [comment]
二维码接口是本地的应该不会出问题的啊，你可以改成其他的
修改二维码接口文件目录为：
第一处：
functions/created   修改71行接口地址，如果想要改变二维码大小只要修改size=数值即可
71：<img src=”https://api.atusu.cn/qr/api.php?text=<?php echo $created_link; ?>&size=200″>
第二处：
根目录/stats 修改87行接口地址，如果想要改变二维码大小只要修改size=数值即可
87:<div class=”col-lg-12″><img alt=”二维码” src=”https://api.atusu.cn/qr/api.php?text=<?php echo $created_link; ?>&size=200″ class=”size center-block”/></div>

**Comment by Zkycardistry** [comment]
> 二维码接口是本地的应该不会出问题的啊，你可以改成其他的
> 修改二维码接口文件目录为：
> 第一处：
> functions/created 修改71行接口地址，如果想要改变二维码大小只要修改size=数值即可
> 71：<img src=”https://api.atusu.cn/qr/api.php?text=&size=200″>
> 第二处：
> 根目录/stats 修改87行接口地址，如果想要改变二维码大小只要修改size=数值即可
> 87:
> 
> <img alt=”二维码” src=”https://api.atusu.cn/qr/api.php?text=&size=200″ class=”size center-block”/>

我照着做了，还是没用

**Comment by urldl** [comment]
你站链接发来看看

**Comment by Zkycardistry** [comment]
> 代码少了，之前发的自动隐藏了不全，再发一次，
> 根目录/functions/created 修改71行接口地址： ` <img src="https://api.atusu.cn/qr/api.php?text=<?php echo $created_link; ?>&size=180">`
> 根目录/stats 修改87行：` <div class="col-lg-12"><img alt="API接口错误请联系管理员！" src="https://api.atusu.cn/qr/api.php?text=<?php echo $created_link; ?>&size=250 " class="size center-block"/></div>`

我昨天就是这么改的，但是还是不行，我现在换别的接口了，可以用了

**Comment by urldl** [comment]
好的，可以了就行，你是不是移动宽带的？如果直接下面这样浏览器访问都打不开，那就是移动的网络问题，测试了下移动宽带和移动4G都不能访问我这个接口，只有联通和电信可以，真TM的移动太垃圾了我都上了三家CDN了只有2个移动节点
`https://api.atusu.cn/qr/api.php?text=https://www.baidu.com/`

**Comment by Zkycardistry** [comment]
我是联通的，直接访问网页倒是可以打开的，之前群里好多人搭建了之后发现二维码都是有问题的，应该不是宽带的问题。

**Comment by urldl** [comment]
那就不清楚了，之前默认的都是本地二维码API就是目录下qr文件夹内的，看有啥问题直接演示站右侧在线客服联系下即可
